### ISSUE TITLE
PyQt 5.14.1 not installing correctly on Travis CI

### ISSUE THREAD

**Issue by marioortizmanero** [vidify/vidify#49]
[Travis CI seems to have trouble when installing PyQt 5.14.1](https://travis-ci.org/marioortizmanero/spotify-music-videos/builds/634007236?utm_source=github_status&utm_medium=notification). I can also reproduce it if I try to install it in a virtual environment (it gets stuck infinitely). Error message:

```
Collecting PyQt5 (from vidify==2.0)
[?25l  Downloading https://files.pythonhosted.org/packages/3a/fb/eb51731f2dc7c22d8e1a63ba88fb702727b324c6352183a32f27f73b8116/PyQt5-5.14.1.tar.gz (3.2MB)

[?25h  Installing build dependencies ... [?25l- \ | / - \ | / - \ done
[?25h  Getting requirements to build wheel ... [?25ldone
[?25h    Preparing wheel metadata ... [?25l- error
    Complete output from command /home/travis/virtualenv/python3.6.7/bin/python /home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpu2kvdctd:
    Querying qmake about your Qt installation...
    /usr/bin/qmake -query
    Traceback (most recent call last):
      File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 64, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
        main()
      File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 67, in prepare_metadata_for_build_wheel
        config_settings)
      File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 95, in _get_wheel_metadata_from_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/tmp/pip-build-env-j3cstft3/overlay/lib/python3.6/site-packages/sipbuild/api.py", line 51, in build_wheel
        project = AbstractProject.bootstrap('pep517')
      File "/tmp/pip-build-env-j3cstft3/overlay/lib/python3.6/site-packages/sipbuild/abstract_project.py", line 82, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "/tmp/pip-build-env-j3cstft3/overlay/lib/python3.6/site-packages/sipbuild/project.py", line 387, in setup
        self.apply_user_defaults(tool)
      File "project.py", line 62, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/tmp/pip-build-env-j3cstft3/overlay/lib/python3.6/site-packages/pyqtbuild/project.py", line 86, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/tmp/pip-build-env-j3cstft3/overlay/lib/python3.6/site-packages/sipbuild/project.py", line 202, in apply_user_defaults
        self.builder.apply_user_defaults(tool)
      File "/tmp/pip-build-env-j3cstft3/overlay/lib/python3.6/site-packages/pyqtbuild/builder.py", line 76, in apply_user_defaults
        self._get_qt_configuration()
      File "/tmp/pip-build-env-j3cstft3/overlay/lib/python3.6/site-packages/pyqtbuild/builder.py", line 463, in _get_qt_configuration
        "v{0}".format(self.qt_version_str))
    sipbuild.exceptions.UserException
    
    ----------------------------------------
[31mCommand "/home/travis/virtualenv/python3.6.7/bin/python /home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpu2kvdctd" failed with error code 1 in /tmp/pip-install-aoy6tfog/PyQt5[0m
[?25htravis_time:end:0822a500:start=1578600256390002797,finish=1578600272333955321,duration=15943952524,event=install
[0K[31;1mThe command "pip3 install .[mpv,dev]" failed and exited with 1 during .[0m
```

This is a tracking issue until this is solved. For now, this module will use 5.14.0.

**Comment by marioortizmanero** [comment]
It seems to be fixed by manually updating pip to the latest version...

**Comment by ryny24** [comment]
I have PIP 20.0.2 but I cannot install PyQt5-5.14.1.tar.gz. with error module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'. :(

**Comment by marioortizmanero** [comment]
Ugh that sucks. My issue was solved almost magically, so I didn't end up knowing what was actually going on. It's definitely an issue with PyQt5, and not with Vidify, though.

What system are you on? Also, have you tried using older versions of PyQt or PySide2?

**Comment by chonix** [comment]
Hey there, just as a heads up, ended up here in this repo by having the same issue.

I solved this by specifying the distribution to be Ubuntu Bionic instead of the default one, which seems to be Xenial

Just added this line at the top of my .travis.yml file
`dist: bionic`

documentation [here](https://docs.travis-ci.com/user/reference/bionic/)

Give it a go and hopefully this will fix that issue :)
Good luck!

**Comment by marioortizmanero** [comment]
Hey @chonix thanks a lot for showing your fix. 

Travis actually works now, so I'll probably leave it like that. Updating pip at the beginning is a good idea anyway. It's probably fixed by specifying Bionic because it's a newer version and it already comes with a more recent pip version.

**Comment by Jeklah** [comment]
Also have this issue.

**Comment by marioortizmanero** [comment]
@Jeklah did you try updating pip?

I could just make PySide2 the default bindings so that these errors happen less...

**Comment by leonardo-menjivar** [comment]
Upgrading pip solved the problem for me

**Comment by Jeklah** [comment]
> @Jeklah did you try updating pip or using PyQt5 5.14.0? Otherwise, just uninstall PyQt5 and PyQtWebEngine and install PySide2.
> 
> I could just make PySide2 the default bindings so that these errors happen less...

I did try both of those. I think I ended up installing Pyside as a workaround. Making it default might be a good idea. Would there be any loss of functionality?

**Comment by marioortizmanero** [comment]
@Jeklah No, PySide is just the same as PyQt5. In my opinion it's even better because it already comes with extensions like the web browser, so you don't have to install PyQtWebEngineWidgets too (or whatever it's called). It's usually less troublesome. 

But PyQt5 is currently as the default because it's the most used amongst the two.

**Comment by levsa** [comment]
I see this error with PyQt 5.14.2 and pip 20.2b1 when trying to install with a debug build of python 3.7.2 (pyenv install 3.7.2 -v).

**Comment by marioortizmanero** [comment]
I expect this issue to happen with all future versions, too. This will go on until the distros update their `pip` packages (for me 5.14.2 worked with pip 20.1.1 after upgrading it). Thanks for the reminder. Did you get it to work?

**Comment by levsa** [comment]
No, unfortunately. I might be doing something wrong. I see that `pip -V` gives correct version, but can it happen that the `pip install --upgrade` misses something? Or does not work with the global installation? The error is always in the same place:

```
Traceback (most recent call last):
      File "/opt/pyenv/versions/3.7.2-debug/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 126, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
```

**Comment by adityanithariya** [comment]
> [Travis CI seems to have trouble when installing PyQt 5.14.1](https://travis-ci.org/marioortizmanero/spotify-music-videos/builds/634007236?utm_source=github_status&utm_medium=notification). I can also reproduce it if I try to install it in a virtual environment (it gets stuck infinitely). Error message:
> 
> ```
> Collecting PyQt5 (from vidify==2.0)
> �[?25l  Downloading https://files.pythonhosted.org/packages/3a/fb/eb51731f2dc7c22d8e1a63ba88fb702727b324c6352183a32f27f73b8116/PyQt5-5.14.1.tar.gz (3.2MB)
> 
> �[?25h  Installing build dependencies ... �[?25l-� �\� �|� �/� �-� �\� �|� �/� �-� �\� �done
> �[?25h  Getting requirements to build wheel ... �[?25ldone
> �[?25h    Preparing wheel metadata ... �[?25l-� �error
>     Complete output from command /home/travis/virtualenv/python3.6.7/bin/python /home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpu2kvdctd:
>     Querying qmake about your Qt installation...
>     /usr/bin/qmake -query
>     Traceback (most recent call last):
>       File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 64, in prepare_metadata_for_build_wheel
>         hook = backend.prepare_metadata_for_build_wheel
>     AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
>     
>     During handling of the above exception, another exception occurred:
>     
>     Traceback (most recent call last):
>       File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
>         main()
>       File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
>         json_out['return_val'] = hook(**hook_input['kwargs'])
>       File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 67, in prepare_metadata_for_build_wheel
>         config_settings)
>       File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 95, in _get_wheel_metadata_from_wheel
>         whl_basename = backend.build_wheel(metadata_directory, config_settings)
>       File "/tmp/pip-build-env-j3cstft3/overlay/lib/python3.6/site-packages/sipbuild/api.py", line 51, in build_wheel
>         project = AbstractProject.bootstrap('pep517')
>       File "/tmp/pip-build-env-j3cstft3/overlay/lib/python3.6/site-packages/sipbuild/abstract_project.py", line 82, in bootstrap
>         project.setup(pyproject, tool, tool_description)
>       File "/tmp/pip-build-env-j3cstft3/overlay/lib/python3.6/site-packages/sipbuild/project.py", line 387, in setup
>         self.apply_user_defaults(tool)
>       File "project.py", line 62, in apply_user_defaults
>         super().apply_user_defaults(tool)
>       File "/tmp/pip-build-env-j3cstft3/overlay/lib/python3.6/site-packages/pyqtbuild/project.py", line 86, in apply_user_defaults
>         super().apply_user_defaults(tool)
>       File "/tmp/pip-build-env-j3cstft3/overlay/lib/python3.6/site-packages/sipbuild/project.py", line 202, in apply_user_defaults
>         self.builder.apply_user_defaults(tool)
>       File "/tmp/pip-build-env-j3cstft3/overlay/lib/python3.6/site-packages/pyqtbuild/builder.py", line 76, in apply_user_defaults
>         self._get_qt_configuration()
>       File "/tmp/pip-build-env-j3cstft3/overlay/lib/python3.6/site-packages/pyqtbuild/builder.py", line 463, in _get_qt_configuration
>         "v{0}".format(self.qt_version_str))
>     sipbuild.exceptions.UserException
>     
>     ----------------------------------------
> �[31mCommand "/home/travis/virtualenv/python3.6.7/bin/python /home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpu2kvdctd" failed with error code 1 in /tmp/pip-install-aoy6tfog/PyQt5�[0m
> �[?25htravis_time:end:0822a500:start=1578600256390002797,finish=1578600272333955321,duration=15943952524,event=install
> �[0K�[31;1mThe command "pip3 install .[mpv,dev]" failed and exited with 1 during .�[0m
> ```
> 
> This is a tracking issue until this is solved. For now, this module will use 5.14.0.

Getting the Same error upgrading pip doesn't helps installing PySide gave another error that it is available only for python version 3.4 and lesser.

**Comment by adityanithariya** [comment]
> No, unfortunately. I might be doing something wrong. I see that `pip -V` gives correct version, but can it happen that the `pip install --upgrade` misses something? Or does not work with the global installation? The error is always in the same place:
> 
> ```
> Traceback (most recent call last):
>       File "/opt/pyenv/versions/3.7.2-debug/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 126, in prepare_metadata_for_build_wheel
>         hook = backend.prepare_metadata_for_build_wheel
>     AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
> ```
> 
> EDIT:
> 
> Running in a docker build:
> 
> ```
> Step 11/43 : RUN pip -V && pip install --global-option=build_ext --global-option="-L/opt/pyenv/versions/3.7.2-debug/lib/ -llibpython3.7dm" pyqt5==5.14.2
>  ---> Running in 520efa81f3e9
> pip 20.1.1 from /opt/pyenv/versions/3.7.2-debug/lib/python3.7/site-packages/pip (python 3.7)
> Collecting pyqt5==5.14.2
>   Downloading PyQt5-5.14.2.tar.gz (3.2 MB)
>   Installing build dependencies: started
> ```

Finally this solved my error
